In [17]:
import pandas as pd

In [18]:
df = pd.DataFrame([[1,2],[1,2]])

In [19]:
from datetime import datetime

In [20]:
round(datetime.now().timestamp())

1670471370

In [21]:
df

0  1
0  1  2
1  1  2

In [22]:
pd.concat([df,df])

0  1
0  1  2
1  1  2
0  1  2
1  1  2

In [23]:
from sensor.utils.main_utils import read_yaml_file

In [24]:
file_path="F:/industry_ready_project1/sensor_fault_detection_mine/sensor-fault-detection/config/schema.yaml"

In [25]:
schema_config = read_yaml_file(file_path=file_path)

In [26]:
len(schema_config['columns'])==len(df.columns)

False

In [27]:
from scipy.stats import ks_2samp

In [28]:
import numpy as np

In [29]:
d1 = np.arange(100,200)
d2 = np.arange(10)

In [30]:
d1

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
       152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
       165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
       178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190,
       191, 192, 193, 194, 195, 196, 197, 198, 199])

In [31]:
d2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
d1

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
       152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
       165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
       178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190,
       191, 192, 193, 194, 195, 196, 197, 198, 199])

In [33]:
d2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
test = ks_2samp(d1,d2)

In [35]:
round(test.pvalue)

0

In [36]:
traing_file_path = "F:/industry_ready_project1/sensor_fault_detection_mine/sensor-fault-detection/artifact/12_08_2022_09_12_52/data_ingestion/ingested/train.csv"

In [37]:
test_file_path = "F:/industry_ready_project1/sensor_fault_detection_mine/sensor-fault-detection/artifact/12_08_2022_09_12_52/data_ingestion/ingested/test.csv"

In [38]:
import pandas as pd

In [39]:
train_df = pd.read_csv(traing_file_path)
test_df = pd.read_csv(test_file_path)

In [40]:
train_df.columns

Index(['class', 'aa_000', 'ab_000', 'ac_000', 'ad_000', 'ae_000', 'af_000',
       'ag_000', 'ag_001', 'ag_002',
       ...
       'ee_002', 'ee_003', 'ee_004', 'ee_005', 'ee_006', 'ee_007', 'ee_008',
       'ee_009', 'ef_000', 'eg_000'],
      dtype='object', length=171)

In [41]:
test_df.columns

Index(['class', 'aa_000', 'ab_000', 'ac_000', 'ad_000', 'ae_000', 'af_000',
       'ag_000', 'ag_001', 'ag_002',
       ...
       'ee_002', 'ee_003', 'ee_004', 'ee_005', 'ee_006', 'ee_007', 'ee_008',
       'ee_009', 'ef_000', 'eg_000'],
      dtype='object', length=171)

In [42]:
from sensor.utils.main_utils import write_yaml_file

In [43]:

def get_drift_report(base_df,current_df,threshold=0.05):
    report ={}
    for column in base_df.columns:
        d1 = base_df[column]
        d2  = current_df[column]
        is_same_dist = ks_2samp(d1,d2)
        if threshold<=is_same_dist.pvalue:
            is_found=False
        else:
            is_found = True 
        report.update({column:{
            "p_value":float(is_same_dist.pvalue),
            "drift_status":is_found
            
            }})
    return report



In [44]:
drift_report = get_drift_report(train_df,test_df)

In [45]:
drift_report

{'class': {'p_value': 1.0, 'drift_status': False},
 'aa_000': {'p_value': 0.0336121691109984, 'drift_status': True},
 'ab_000': {'p_value': 0.8077738928808008, 'drift_status': False},
 'ac_000': {'p_value': 0.22346374147882053, 'drift_status': False},
 'ad_000': {'p_value': 0.40420469588802277, 'drift_status': False},
 'ae_000': {'p_value': 0.9999999893421427, 'drift_status': False},
 'af_000': {'p_value': 0.999999998337216, 'drift_status': False},
 'ag_000': {'p_value': 1.0, 'drift_status': False},
 'ag_001': {'p_value': 0.999999999999922, 'drift_status': False},
 'ag_002': {'p_value': 0.9999999997996436, 'drift_status': False},
 'ag_003': {'p_value': 0.12920906054192238, 'drift_status': False},
 'ag_004': {'p_value': 0.0760864583952896, 'drift_status': False},
 'ag_005': {'p_value': 0.08405417218830147, 'drift_status': False},
 'ag_006': {'p_value': 0.3284187068653508, 'drift_status': False},
 'ag_007': {'p_value': 0.2363287425080175, 'drift_status': False},
 'ag_008': {'p_value': 0.

In [46]:
write_yaml_file(file_path=os.path.join(os.getcwd(),"report.yaml"),content=drift_report,replace=True)

In [47]:
d1 = train_df['class']
d2  = test_df['class']
ks_2samp(d1,d2)

KstestResult(statistic=0.0017289292121173139, pvalue=1.0)

KstestResult(statistic=0.009896540089462558, pvalue=0.6183763526162667)

In [1]:
from sensor.ml.model.estimator import TargetValueMapping

In [4]:
.to_dict()TargetValueMapping()

{'neg': 0, 'pos': 1}

In [5]:
TargetValueMapping().reverse_mapping()

{0: 'neg', 1: 'pos'}